[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn core.wsgi:application"
healthcheckPath = "/api/health/"
restartPolicy = "on-failure"

[deploy.env]
DJANGO_SETTINGS_MODULE = "core.settings_prod"
DEBUG = "False"
ALLOWED_HOSTS = ".railway.app"

[[services]]
name = "web"
envs = [
  "DATABASE_URL",
  "REDIS_URL",
  "ELASTICSEARCH_HOSTS",
  "DJANGO_SECRET_KEY",
  "RAILWAY_VOLUME_ACCESS_KEY",
  "RAILWAY_VOLUME_SECRET_KEY",
  "RAILWAY_VOLUME_NAME",
  "RAILWAY_VOLUME_ENDPOINT",
  "SENTRY_DSN"
]

[[services]]
name = "redis"
image = "redis:6"

[[services]]
name = "elasticsearch"
image = "docker.elastic.co/elasticsearch/elasticsearch:7.14.0"
envs = [
  "discovery.type=single-node",
  "ES_JAVA_OPTS=-Xms512m -Xmx512m"
] 